src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Membre $id_membre = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicule $id_vehicule = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_fin = null;

    #[ORM\Column]
    private ?int $prix_total = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMembre(): ?Membre
    {
        return $this->id_membre;
    }

    public function setIdMembre(?Membre $id_membre): self
    {
        $this->id_membre = $id_membre;

        return $this;
    }

    public function getIdVehicule(): ?Vehicule
    {
        return $this->id_vehicule;
    }

    public function setIdVehicule(?Vehicule $id_vehicule): self
    {
        $this->id_vehicule = $id_vehicule;

        return $this;
    }

    public function getDateHeureDepart(): ?\DateTimeInterface
    {
        return $this->date_heure_depart;
    }

    public function setDateHeureDepart(\DateTimeInterface $date_heure_depart): self
    {
        $this->date_heure_depart = $date_heure_depart;

        return $this;
    }

    public function getDateHeureFin(): ?\DateTimeInterface
    {
        return $this->date_heure_fin;
    }

    public function setDateHeureFin(\DateTimeInterface $date_heure_fin): self
    {
        $this->date_heure_fin = $date_heure_fin;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['pseudo'], message: 'There is already an account with this pseudo')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'id_membre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setIdMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdMembre() === $this) {
                $commande->setIdMembre(null);
            }
        }

        return $this;
    }
}

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use DateTime;
use DateInterval;
use App\Entity\Commande;
use App\Form\CommandePostType;
use App\Repository\MembreRepository;
use App\Repository\CommandeRepository;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AgenceController extends AbstractController
{
    #[Route('/', name: 'app_agence')]
    public function index(VehiculeRepository $repo): Response
    {
        $vehicules = $repo->findAll();
    
        return $this->render('agence/index.html.twig', [
            'controller_name' => 'AgenceController',
            'vehicules' => $vehicules
        ]);
    }
    
    #[Route("/agence/show/{id}", name:"vehicule_show")]
    public function show($id, VehiculeRepository $repo, Request $globals, EntityManagerInterface $manager)
    {
        $vehicule = $repo->find($id);
                
        $commande = new Commande;
        $form=$this->createForm(CommandePostType::class, $commande);
        $form->handleRequest($globals);
        
        if($form->isSubmitted() && $form->isValid())
        {
            $debut=$commande->getDateHeureDepart();
            $fin=$commande->getDateHeureFin();

            $interval = $debut->diff($fin);
            $days=$interval->days;
            $prix = $vehicule->getPrixJournalier();
            $prix = $prix * $days;

            if($prix < 0)
            {
                $this->addFlash('warning', "votre commande n'a pas été validé, vous avez choisie une date de fin antérieur la date de début");
                return $this->redirectToRoute('vehicule_show');
            }
            $commande->setPrixTotal($prix);
            $commande->setDateEnregistrement(new \DateTime);
            $commande->setIdVehicule($vehicule);
            $commande->setIdMembre($this->getUser());
            $manager->persist($commande);
            $manager->flush();
            $this->addFlash('success', "votre commande a bien été accepté");
            return $this->redirectToRoute('app_agence');
        }
        return $this->renderForm('agence/show_vehicule.html.twig', [
            'item' => $vehicule,
            'formCommande' => $form,
        ]);
        }

        #[Route("/profil", name: "app_profil")]
        public function profil(CommandeRepository $repo, EntityManagerInterface $manager, Request $globals, VehiculeRepository $repoVehicule, MembreRepository $repoMembre, Commande $commande = null)
        {
            if($commande == null):
                $commande = new Commande;              
            endif;
            $commandes = $repo->findAll();
            
            $form = $this->createForm(CommandePostType::class, $commande);
            $form->handleRequest($globals);
    
    
            return $this->renderForm("agence/profil.html.twig",[
                'commandes' => $commandes,
                "formCommande" => $form,
            ]);
                    
        }
        
        #[Route("/profil/commande/delete/{id}", name: 'user_delete_commande')]
        public function deleteComande(Commande $commande, EntityManagerInterface $manager)
        {
            $manager->remove($commande);
            $manager->flush();
            $this->addFlash('success',"La commande a bien été supprimé");
            return $this->redirectToRoute("profil");
        }
    
    
}

templates/agence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AgenceLoc{% endblock %}

{% block body %}
  <div class="container border border-info text-white mt-2">
{% if app.user %}
  <h2>Bienvenue sur notre site {{app.user.pseudo}}, une nouvelle location de prévue ? Nous avons surement le véhicule qu'il vous faut !</h2>
{% else %}
  <h2>Bienvenue sur notre site, connectez-vous pour louer la voiture de vos rêve !</h2>
{% endif %}
  </div>

<div class="container m-4 "> 
{% for item in vehicules %}
<div class="card text-white mb-3 mx-auto"
style="max-width: 20rem;">
  <div class="card-header text-center"> {{ item.title }} </div>
  <div class="card-body text-center">
    <h4 class="card-title"> {{ item.marque }} {{item.modele}}</h4>
    <img class="text-center" src="{{ item.photo }}" alt="" width="200px">
    <p class="card-text"> {{ item.description }} </p>
    <hr>
    <p>Prix Journalier : {{ item.prixjournalier }} €</p>

    <a href="{{path('vehicule_show', {id:item.id})}}" class="btn btn-success">Voire et commander</a>
  </div>
</div>
{% endfor %}
</div>


{% endblock %}

templates/agence/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil {{app.user.pseudo}}{% endblock %}

{% block body %}

<h1>Mon profil</h1>
<div class="card mb-3 text-center">
  <h3 class="card-header"> {{ app.user.pseudo }} </h3>
  <div class="card-body">
    <h5 class="card-title">{{ app.user.prenom }} {{ app.user.nom }}</h5>
    <h5 class="card-title"> {{ app.user.email }} </h5>
  </div>
  <div class="card-body">
  <p class="card-header"> genre : {{ app.user.civilite }} </p>
  </div>
  <div class="card-footer text-muted">
    (Membre depuis le {{ app.user.dateenregistrement|date("d/m/Y à H:i:s") }})
  </div>
</div>


<h2>Mes commandes</h2>
{% for commande in commandes %}
    {% if commande.idMembre.id == app.user.id %}
        <div class="card mb-3 text-center">
            <div class="card-header">
                <h3>Commande du {{commande.dateEnregistrement|date("d/m/Y à H:i:s")}}</h3>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{commande.idvehicule.title}}</h4>
                <p class="card-text">
                -heure de départ : {{commande.dateheuredepart|date("d/m/Y à H:i")}}<br>
                -heure de fin : {{commande.dateheurefin|date("d/m/Y à H:i")}}
                </p>
                <div class="container">
                <p>{{commande.idvehicule.marque}} {{commande.idvehicule.modele}}</p>
                <img src="{{commande.idvehicule.photo}}" alt="Photo du vehicule à louer" width="50%">
                <p>prix total : {{commande.prixtotal}} €</p>
                </div>
            </div>
        </div>    
    
    {% endif %}

{% endfor %}

{% endblock %}

templates/agence/show_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande!{% endblock %}

{% block body %}
<div class="card mb-3 text-center">
  <h3 class="card-header">Commande n° {{ commande.id }} </h3>
  <div class="card-body">
    <h5 class="card-title">{{ commande.idmembre.prenom}} - {{ commande.idmembre.nom}} - {{ commande.idmembre.email}} </h5>
    <h5 class="card-title"> {{ commande.idvehicule.marque}} - {{ commande.idvehicule.modele}} </h5>
  </div>
  <div class="card-body">
  <p class="card-header"> début de réservation le {{ commande.dateheuredepart|date("d/m/Y à H:i") }} </p>
  <p class="card-header"> fin de réservation le {{ commande.dateheurefin|date("d/m/Y à H:i") }} </p>
  </div>
  <div class="card-footer text-muted">
    (Commande passée le {{ commande.dateenregistrement|date("d/m/Y à H:i:s") }})
  </div>
</div>



{% endblock %}

templates/agence/show_membre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil {{app.user.pseudo}}{% endblock %}

{% block body %}
<div class="card mb-3 text-center">
  <h3 class="card-header"> {{ membre.pseudo }} </h3>
  <div class="card-body">
    <h5 class="card-title">{{ membre.prenom }} {{ membre.nom }}</h5>
    <h5 class="card-title"> {{ membre.email }} </h5>
  </div>
  <div class="card-body">
  <p class="card-header"> genre : {{ membre.civilite }} </p>
  </div>
  <div class="card-footer text-muted">
    (Membre depuis le {{ membre.dateenregistrement|date("d/m/Y à H:i:s") }})
  </div>
</div>



{% endblock %}

templates/agence/show_vehicule.html.twig
{% extends 'base.html.twig' %}

{% block title %}AgenceLoc {{item.title}}{% endblock %}

{% block body %}
<div class="card mb-3 text-center">
  <h3 class="card-header"> {{ item.title }} </h3>
  <div class="card-body">
    <h5 class="card-title">{{ item.marque }} {{ item.modele }}</h5>
    <h5 class="card-title"> Prix Journalier {{ item.prixjournalier }} € </h5>
  </div>
  <div class="text-center">
    <img src="{{ item.photo }}" alt="" width="50%" height="50%">
  </div>
  <div class="card-body">
  <p class="card-header"> Description : </p>
    <p class="card-text"> {{ item.description }} </p>
  </div>
  <div class="card-footer text-muted">
    (Ajoutée le {{ item.dateenregistrement|date("d/m/Y à H:i:s") }})
  </div>
{% if app.user %}
  
{{form_start(formCommande, {
    attr: {
        novalidate: 'novalidate'
    }
})}}
<div class="row d-flex justify-content-evenly">
<div class="col-md-3">
{{form_row(formCommande.date_heure_depart)}}
</div>
<div class="col-md-3">
{{form_row(formCommande.date_heure_fin)}}
</div>
</div>
<button type="submit" class="btn btn-primary mt-2">
    Commander
</button>

{{form_end(formCommande)}}
{% else %}
<p><a href="{{path('app_login')}}">Connectez-vous</a> pour commander</p>
  
{% endif %}
</div>



{% endblock %}